---
language: python
python: "3.6"

sudo: required

services:
  - docker

install:
  - pip install -r requirements-test.txt

script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
