---

- name: Jenkins | Configure csrf
  jenkins_script:
    script: "{{ lookup('file', 'security/CSRFConfiguration.groovy') }}"
    user: "{{ jenkins_admin_username }}"
    password: "{{ jenkins_admin_password }}"
    url: "{{ jenkins_url }}"
    args:
      crumb_enabled: "{{ jenkins_crumb_enabled | default(false) }}"

- name: Jenkins | Configure Agent
  jenkins_script:
    script: "{{ lookup('file', 'security/' + item + '.groovy') }}"
    user: "{{ jenkins_admin_username }}"
    password: "{{ jenkins_admin_password }}"
    url: "{{ jenkins_url }}"
  with_items:
    - ConfigureAgent
  
- name: Jenkins | Configure default users
  template:
    src: CreateInitialCredentials.groovy.j2
    dest: "{{ jenkins_init_scripts_path }}/CreateInitialCredentials.groovy"
  when: jenkins_check.changed | bool
  tags:
    skip_ansible_lint
