---
# JAVA
java_implementation: openjdk
java_open_jdk_version: 8u252-b09-1~deb9u1
java_open_jdk_set_version: 8

# Cannot test jenkins_slaves in docker:
# https://github.com/ansible/ansible/issues/23727
# jenkins_slaves:
#   - name: slave1
#     hostname: jenkins-slave.vm
#     description: first slave
#     executors: 2
#     label: slave1
#     credentials: jenkins
#     home: "{{ jenkins_home_path }}"

java_open_jdk_home: /usr/lib/jvm/java-8-openjdk-amd64

jenkins_settings_java:
  - implementation: openjdk
    versions:
      - name: 8
        home: "{{ java_open_jdk_home }}"

jenkins_settings_groovy:
  - version: '2.2.1'

jenkins_settings_maven:
 - version: '3.3.9'

jenkins_plugins:
  - { name: "nodejs", version: "1.3.9"}
  - { name: "config-file-provider", version: "3.7.0"}
  - { name: "token-macro", version: "2.12"}
  - { name: "workflow-step-api", version: "2.23"}
  - { name: "bouncycastle-api", version: "2.18"}
  - { name: "command-launcher", version: "1.5"}
  - { name: "msbuild", version: "1.29"}
  - { name: "jdk-tool", version: "1.4"}
  - { name: "ssh-credentials", version: "1.18.1"}
  - { name: "matrix-project", version: "1.18"}
  - { name: "bootstrap4-api", version: "4.5.3-1"}
  - { name: "plugin-util-api", version: "1.4.0"}
  - { name: "echarts-api", version: "4.9.0-2"}
  - { name: "jackson2-api", version: "2.11.3"}
  - { name: "checks-api", version: "1.1.0"}
  - { name: "workflow-api", version: "2.40"}
  - { name: "jquery3-api", version: "3.5.1-2"}
  - { name: "popper-api", version: "1.16.0-7"}
  - { name: "font-awesome-api", version: "5.15.1-1"}
  - { name: "snakeyaml-api", version: "1.27.0"}
  - { name: "workflow-cps", version: "2.85"}
  - { name: "workflow-job", version: "2.40"}
  - { name: "ace-editor", version: "1.1"}
  - { name: "workflow-scm-step", version: "2.11"}
  - { name: "workflow-support", version: "3.6"}
  - { name: "jquery-detached", version: "1.2.1"}

jenkins_script_parameters:
  NodeJS:
    versions:
      - grunt:
        name: 'grunt'
        version: '9.11.1'
        pkgs: 'grunt-cli'
        refresh: 72
      - bower:
        name: 'bower'
        version: '0.10.24'
        pkgs: 'bower'
        refresh: 72
  MSBuild:
    versions:
      - errorsOnly:
        name: MSBuild 15.0 ErrorsOnly
        path: C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\MSBuild\\15.0\\Bin\\MSBuild.exe
        params: /clp:ErrorsOnly /p:Configuration=Release /p:DebugSymbols=false
      - deploy:
        name: MSBuild 15.0 ErrorsOnly and Deploy
        path: C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\MSBuild\\15.0\\Bin\\MSBuild.exe
        params: /clp:ErrorsOnly  /T:Build,Package /p:Configuration=Release /p:DebugSymbols=false


jenkins_use_jobdsl: true
