---

- name: restart jenkins
  systemd:
    name: jenkins
    state: restarted
  when: jenkins_service_state != 'stopped'

- name: safe restart jenkins
  jenkins_script:
    script: "{{ lookup('file', 'security/SafeRestart.groovy') }}"
    user: "{{ jenkins_admin_username }}"
    password: "{{ jenkins_admin_password }}"
    url: "{{ jenkins_url }}"
