---
- hosts: jenkinsslave
  pre_tasks:
    - name: Jenkins Slave | PRE_TASKS | Install required libs
      apt:
        pkg: "{{ item }}"
        state: installed
        update_cache: true
        cache_valid_time: 600
      loop:
        - openssh-client
        - openssh-server
    - name: Jenkins Slave | PRE_TASKS | Configuring service
      systemd:
        name: ssh
        state: restarted
      changed_when: false

- hosts: jenkinsmaster
  roles:
    - jenkins_role

